name: Lint the YML files

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Runs the YML file checker
        run: yamllint -f standard -c ./.github/ymllint-config.yml ./modules/SilkSpawners/src/main/resources
